require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.2
  NewCops: enable
  ActiveSupportExtensionsEnabled: true
  Include:
    - '**/*.rake'
    - '**/*.rb'
    - '**/Rakefile'
    - '**/Gemfile'
    - '**/*.gemfile'
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Rails/ApplicationController:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

Lint/NonAtomicFileOperation:
  Enabled: true
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/*_spec.rb'

RSpec/ExampleLength:
  Max: 10

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true
  CountKeywordArgs: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Style/HashConversion:
  Enabled: true

Layout/LineLength:
  Max: 140

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Performance/ChainArrayAllocation:
  Enabled: true

Style/AutoResourceCleanup:
  Enabled: true

Style/ExpandPathArguments:
  Enabled: true

Style/ReturnNil:
  Enabled: true

Style/UnlessLogicalOperators:
  Enabled: true

Style/MethodCallWithArgsParentheses:
  Enabled: true
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
  EnforcedStyle: omit_parentheses

Style/SuperWithArgsParentheses:
  Enabled: false

Style/Documentation:
  Enabled: false
