name: Run Linters
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      BUNDLE_GEMFILE: './gemfiles/rails_7.2.gemfile'
    steps:
    - uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true

    - name: Setup gems
      run: |
        bundle install --jobs 4 --retry 3

    - name: Run RuboCop
      run: |
        bundle exec rubocop -S
