name: Tests
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ruby: ['3.1', '3.2', '3.3']
        rails: ['7.2.0', '8.0.0']
        middleware: ['false', 'true']
        exclude:
          - ruby: '3.1'
            rails: '8.0.0'

    env:
      MIDDLEWARE: ${{ matrix.middleware }}
      RAILS_VERSION: ${{ matrix.rails }}
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup smtp_mock for ruby
        run: |
          bundle exec smtp_mock -i ~

      - name: Test smtp_mock for ruby
        run: |
          bundle exec smtp_mock --version

      - name: Run tests
        run: bundle exec rake
